Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/08/2020
Var
idade,numerodias:real


Inicio
numerodias <- 360
escreva("escreva sua idade")
leia(idade)
idade<- (idade * numerodias)
escreva("seus dias de vida", idade)



Fimalgoritmo