Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/08/2020
Var
A,B,C:inteiro

Inicio
escreva("Digite um numero A:")
leia(A)
escreva("Digite um numero B:")
leia (B)
C <- A
A <- B
B <- C
escreval("NUMERO A É:",A)
escreval("NUMERO B É:",B)



Fimalgoritmo