Algoritmo "exercicio 06"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/08/2020
Var
 vel,km,ms:real
 


Inicio
escreva("digite a velocidade em km")
leia(km)
ms<- (km/3.6)
escreval (ms)
vel<-(434.4/km)
escreval("o tempo a ser percorrido até o rio jáneiro é",vel)



Fimalgoritmo