Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/08/2020
Var
temperatura:inteiro


Inicio
escreva("Qual a Temperatura??")
leia (temperatura)
escreval("a temperatura é",temperatura)
se (temperatura >=25) entao
escreval("esta muito quente")
senao
escreval("a temperatura esta agradavel")
fimse

Fimalgoritmo