Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/08/2020
Var
numero:inteiro


Inicio
escreva("Digite um Numero")
leia(numero)
se(numero mod 2) = 0 entao
escreval(numero," - é um numero par")
senao
escreval(numero," - é um numero impar")
fimse








Fimalgoritmo