Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/08/2020
Var
temperatura:inteiro


Inicio
escreva("digite um numero")
leia(temperatura)
se (temperatura >= 25)entao
escreval("esta muito calor")
senao
escreval("esta agradavel")
fimse


Fimalgoritmo