Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/08/2020
Var
valorFX,valorFC:inteiro


Inicio
escreva("digite o Valor Fixado:")
leia(valorFX)
escreva("digite o valor Funcionario:")
leia(valorFC)
se (valorFC >= valorFX) entao
escreval("GANHOU")
senao
escreval("NÃO GANHOU")
FIMSE


Fimalgoritmo