Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/08/2020
Var
n1:inteiro


Inicio
escreva("digite um numero:")
leia(n1)
se(n1  mod 2)= 0 então
escreval(n1," - é um numero par")
senao
escreval(n1," - é um numero impar")
fimse


Fimalgoritmo