Algoritmo "semnome"

Var
nota1,nota2,nota3,nota4,Nome,idade,media: real


Inicio
escreva("Qual seu nome:")
leia (nome)
escreva("Qual sua Idade")
leia (idade)
escreva("Digite a nota 1:")
leia(nota1)

escreva("Digite a nota 2:")
leia (nota2)

escreva("Digite a nota 3:")
leia (nota3)

escreva("Digite a nota 4:")
leia(nota4)

media <- ((nota1+nota2+nota3+nota4)/4)

escreval("sua media é =",media)




Fimalgoritmo